sh StartMultipleCueEstimation.sh "Datasets/entry-P10" "png"
sh StartMultipleCueEstimation.sh "Datasets/castle-P30" "png"
sh StartMultipleCueEstimation.sh "Datasets/fountain-P11" "png"
sh StartMultipleCueEstimation.sh "Datasets/Herz-Jesu-P8" "png"
sh StartMultipleCueEstimation.sh "Datasets/rathaus" "ppm"
sh StartMultipleCueEstimation.sh "Datasets/semper" "ppm"
#sh StartMultipleCueEstimation.sh "Datasets/brussles"
